# Generated by Django 4.1 on 2022-09-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_username_userlog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='user',
            new_name='username',
        ),
    ]
